set nocompatible              " be iMproved, required
filetype off                  " required

set relativenumber
set number

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" my plugins

" jedi autocomplete
Plugin 'davidhalter/jedi-vim'

" supertab tab for completion
Plugin 'ervandew/supertab'

" file access
Plugin 'kien/ctrlp.vim'

" flake8 the code
Plugin 'nvie/vim-flake8'

" pep8 indentations
Plugin 'hynek/vim-python-pep8-indent'

" surround
Plugin 'tpope/vim-surround'

" nerdtree
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" general config

" Rebind <Leader> key
" " I like to have it here becuase it is easier to reach than the default and
" " it is next to ``m`` and ``n`` which I use for navigating between tabs.
let mapleader = ","

" easier moving between tabs
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>

"ipdb
map <Leader>b Oimport ipdb; ipdb.set_trace() # BREAKPOINT<C-c>

" fixes
let g:SuperTabDefaultCompletionType = "<c-n>"
let g:jedi#usages_command = "<leader>u"

" We/I follow pep8 except the line length crazyness
" It is setup in ~/config/flake8

" show a mark for each flake8 violation not the windows
let g:flake8_show_in_file=1
let g:flake8_show_in_gutter=1
let g:flake8_show_quickfix=0

" run flake8 on file after saving
" let g:flake8_cmd="/usr/bin/flake8"
autocmd BufWritePost *.py call Flake8()

" remove trailing whitespaces...
autocmd BufWritePre *.py :%s/\s\+$//e

" Disable backup and swap files
set nobackup
set nowritebackup
set noswapfile

set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set shiftround
set expandtab
set backspace=indent,eol,start

set pastetoggle=<F2>

nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>
imap jj <Esc>
nnoremap ; :
nnoremap : ;

noremap cc :s/^/#/<CR>
noremap rc :s/^#//<CR>

nnoremap * :set hlsearch<CR>*
nnoremap # :set hlsearch<CR>#

" Move visual block
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

function RebaseActionToggle()
    let line = getline(".")
    let result = matchstr(line, "^\\a")
    let transitions = {'p': 'squash', 's': 'edit', 'e': 'fixup', 'f': 'pick'}
    execute "normal! ^cw" . transitions[result]
    execute "normal! ^"
endfunction

noremap r<Cr> :call RebaseActionToggle()<Cr>

set undofile " Maintain undo history between sessions
set undodir=~/.vim/undodir
